baseURL: "https://darve.sh"
title: Darvesh
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: false

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Posts
          url: posts
          weight: 1
        - name: What I use
          url: tools
          weight: 2
        - name: Search
          url: search/
          weight: 3
        - name: Tags
          url: tags/
          weight: 4
        - name: Categories
          url: categories/
          weight: 5
       
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Darvesh - https://github.com/darvesh/darvesh.sh"
  author: Darvesh

  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: true
  disableSpecial1stPost: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  comments: false
  images: ["cover.png"]

  profileMode:
    enabled: false
    title: Darvesh
    imageUrl: "home.svg"
    imageTitle: myimage
    imageWidth: 300
    imageHeight: 300
    buttons:
      - name: Github
        url: https://github.com/darvesh
        new_page: true
      - name: Posts
        url: /posts
        new_page: false

  homeInfoParams:
    Title: "Hello there, I'm Darvesh"
    Content: >
      NodeJS | Deno | TypeScript | JavaScript | Rust | Life | Travel

  socialIcons:
    - name: github
      url: "https://github.com/darvesh"
    - name: Stackoverflow
      url: "https://stackoverflow.com/users/8892700/darvesh"
    - name: KoFi
      url: "https://ko-fi.com/darvesh"
    - name: LinkedIn
      url: https://www.linkedin.com/in/drvsh/
    - name: RsS
      url: "index.xml"

  assets:
    favicon: "favicon/favicon.ico"
    favicon16x16: "favicon/favicon-16x16.png"
    favicon32x32: "favicon/favicon-32x32.png"
    apple_touch_icon: "favicon/apple-icon.png"
    safari_pinned_tab: "favicon/apple-icon.png"

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: false
    style: monokai
